---
apiVersion: elastic.iml.github.io/v1alpha1
kind: ElasticJob
metadata:
  name: fine-tuning-llama2
  namespace: dlock
spec:
  distributionStrategy: AllreduceStrategy
  optimizeMode: single-job
  replicaSpecs:
    worker:
      replicas: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              # yamllint disable-line rule:line-length
              image: dlock/llama3:fine
              imagePullPolicy: Never
              command:
                - /bin/bash
                - -c
                - "dlock-run --nnodes=$NODE_NUM \
                  --nproc_per_node=1 --max_restarts=1  \
                  ./examples/llama3/transformer_train.py  \
                  ./examples/llama3/alpaca_en_demo.json \
                  ./examples/llama3/Llama-3-1B"
              resources:
                limits:
                  cpu: "8"
                  memory: 16Gi
                  nvidia.com/gpu: 1  # optional
                requests:
                  cpu: "4"
                  memory: 16Gi
                  nvidia.com/gpu: 1  # optional