---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dlock-data-store
  namespace: dlock
data:
  # yamllint disable
  datastore: |
    base_datastore:
      db.user: "root"
      db.password: "root"
      db.engine.type: "mysql"
      db.url: "tcp(mysql:3306)/dlock?parseTime=true&interpolateParams=true&loc=Local"
    elasticjob_datastore:
      db.user: "root"
      db.password: "root"
      db.engine.type: "mysql"
      db.url: "tcp(mysql.dlock.svc.cluster.local:3306)/dlock?parseTime=true&interpolateParams=true&loc=Local"
  # yamllint enable