---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dlock-kube-monitor
  namespace: dlock
data:
  config: |
    namespace: "dlock"
    data-store.config-map.name: "dlock-data-store"
    data-store.config-map.key: "datastore"
    kube-watcher.handler.config-map.name: "dlock-k8s-watch-handler"
    kube-watcher.handler.config-map.key: "handler"
